modules:
  idrepo:
    enabled: true
    image:
      repository: mosipid/apitest-idrepo
      tag: 1.3.x
      pullPolicy: Always

  prereg:
    enabled: false

  masterdata:
    enabled: false

  partner:
    enabled: false

  pms:
    enabled: false

  resident:
    enabled: false

  auth:
    enabled: false

  esignet:
    enabled: false

  mimoto:
    enabled: false
