apiVersion: v2
name: idrepo-saltgen
description: A Helm chart to generate salt for ID Repo.
type: application
version: 12.2.0-develop
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - idrepo
  - salt

maintainers:
  - email: info@mosip.io
    name: MOSIP
