apiVersion: v2
name: credentialfeeder
description: A Helm chart to generate keys
type: application
version: 1.3.0-develop
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - keymanager
  - credentialfeeder
  - kernel
maintainers:
  - email: info@mosip.io
    name: MOSIP
