apiVersion: v2
name: identity
description: A Helm chart for MOSIP IDRepo Identity Service
type: application
version: 12.2.0-develop
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - identity
  - kernel
maintainers:
  - email: info@mosip.io
    name: MOSIP
